# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-09 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RowingWorkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=120)),
                ('meters', models.CharField(max_length=120)),
                ('notes', models.CharField(max_length=420)),
            ],
        ),
    ]
