# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-09 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rowingworkout',
            name='notes',
            field=models.CharField(blank=True, max_length=420, null=True),
        ),
    ]
