# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-09 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_auto_20171209_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rowingworkout',
            name='meters',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rowingworkout',
            name='time',
            field=models.IntegerField(),
        ),
    ]
